CREATE TABLE IF NOT EXISTS servers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT '停止中',
  cpu_usage NUMERIC(5, 2) DEFAULT 0,
  memory_usage NUMERIC(5, 2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);